Repository gardener/landscapercli, pull requests merged in 2022-01, with the labels that each got.

#112 fix gitTreeState; was always returning dirty
  hack/install-cli.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#114 Fix issue with parent directory calculation
  cmd/components/add_helm_ls_deployitem.go
  cmd/components/create.go
  pkg/components/resource_writer.go
Labels: kind/test, reviewed/lgtm, needs/ok-to-test, size/s

#118 updates jsonschema handling
  cmd/installations/create.go
  go.mod
  go.sum
  pkg/jsonschema/resolver.go
  pkg/jsonschema/resolver_test.go
  pkg/jsonschema/testdata/registry/blobs/distinct-component-my-type/distinct-component-my-type.json
  pkg/jsonschema/testdata/registry/blueprint-fs/blueprint/blueprint.yaml
  pkg/jsonschema/testdata/registry/blueprint-fs/blueprint/my-type.json
  pkg/jsonschema/testdata/registry/blueprint-fs/component-descriptor.yaml
  pkg/jsonschema/testdata/registry/cyclic-ref/blueprint/blueprint.yaml
  pkg/jsonschema/testdata/registry/cyclic-ref/blueprint/my-type.json
  pkg/jsonschema/testdata/registry/cyclic-ref/component-descriptor.yaml
  pkg/jsonschema/testdata/registry/distinct-component-bp/blueprint/blueprint.yaml
  pkg/jsonschema/testdata/registry/distinct-component-bp/component-descriptor.yaml
  pkg/jsonschema/testdata/registry/distinct-component-schema/component-descriptor.yaml
  pkg/jsonschema/testdata/registry/inline/blueprint/blueprint.yaml
  pkg/jsonschema/testdata/registry/inline/component-descriptor.yaml
  pkg/jsonschema/testdata/registry/local-types/blueprint/blueprint.yaml
  pkg/jsonschema/testdata/registry/local-types/component-descriptor.yaml
  vendor/github.com/gardener/component-cli/pkg/utils/utils.go
  vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/kubernetes/kubernetes.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/execution/reconcile.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/installations/operation.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/installations/subinstallations/subinstallations.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/jsonschema/loader.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/jsonschema/reference.go
  vendor/github.com/gardener/landscaper/pkg/landscaper/jsonschema/validate.go
  vendor/github.com/gardener/landscaper/pkg/utils/builders.go
  vendor/github.com/gardener/landscaper/pkg/utils/landscaper/blueprint.go
  vendor/github.com/gardener/landscaper/test/utils/envtest/environment.go
  vendor/github.com/gardener/landscaper/test/utils/envtest/types.go
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/xl

#122 Render blueprint with local resources
  cmd/blueprints/render.go
  cmd/components/add_container_deployitem.go
  cmd/components/add_helm_ls_deployitem.go
  docs/reference/landscaper-cli_blueprints_render.md
  go.mod
  go.sum
  pkg/components/resource_reader.go
  pkg/resolver/render_blob_resolver.go
  pkg/resolver/render_component_resolver.go
  pkg/resolver/util.go
  pkg/resolver/util_test.go
  vendor/github.com/gardener/landscaper/pkg/utils/landscaper/blueprint.go
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/l

#123 Render blueprint documentation
  docs/commands/blueprints/render.md
  docs/examples/render-blueprint/01-render-with-values/blueprint/blueprint.yaml
  docs/examples/render-blueprint/01-render-with-values/render.sh
  docs/examples/render-blueprint/01-render-with-values/values.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/m
