Repository gardener/landscapercli, pull requests merged in 2022-05, with the labels that each got.

#142 Update to alpine:3.15
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#145 integration test cleanup
  integration-test/main.go
  integration-test/tests/test_component_create.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#143 Component-CLI update to 0.40.0
  docs/reference/landscaper-cli_component-cli_component-archive.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_add-digests.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_check-digests.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_sign.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_sign_rsa.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_sign_signing-server.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_verify.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_verify_rsa.md
  docs/reference/landscaper-cli_component-cli_component-archive_signature_verify_x509.md
  go.mod
  go.sum
  vendor/github.com/gardener/component-cli/cmd/component-cli/app/app.go
  vendor/github.com/gardener/component-cli/ociclient/client.go
  vendor/github.com/gardener/component-cli/ociclient/copy.go
  vendor/github.com/gardener/component-cli/ociclient/types.go
  vendor/github.com/gardener/component-cli/ociclient/utils.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/componentarchive.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/resources/add.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/add_digests.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/check_digests.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/rsa.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/sign.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/signing_server.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/signature.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/verify/rsa.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/verify/verify.go
  vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/verify/x509_certificate.go
  vendor/github.com/gardener/component-cli/pkg/signatures/digester.go
  vendor/github.com/gardener/component-cli/pkg/signatures/signing_server.go
  vendor/github.com/gardener/component-cli/pkg/signatures/util.go
  vendor/github.com/gardener/component-cli/pkg/signatures/x509_certificate.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/accesstypes.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/cdutils/utils.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/componentdescriptor.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/default.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/signatures/normalize.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/signatures/rsa.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/signatures/sign.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/signatures/types.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/unstructured.go
  vendor/github.com/gardener/image-vector/pkg/imagevector.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/second-opinion, size/l
