Repository gardener/landscapercli, pull requests merged in 2022-03, with the labels that each got.

#129 automatic landscaper version determination
  Makefile
  hack/cross-build.sh
  hack/install-cli.sh
Labels: needs/ok-to-test, needs/review, size/xs

#131 Force delete
  cmd/installations/force_delete.go
  cmd/installations/inspect.go
  cmd/installations/installations.go
  docs/reference/landscaper-cli_installations.md
  docs/reference/landscaper-cli_installations_force-delete.md
  pkg/util/k8sclient.go
Labels: needs/ok-to-test, needs/review, size/m

#133 Improve force-delete command
  cmd/installations/force_delete.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
